/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal.paneles;

import com.mycompany.proyectofinal.ProyectoFinal;
import com.mycompany.proyectofinal.models.Curso;
import com.mycompany.proyectofinal.models.Estudiante;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author donovanpc
 */
public class Panel_Consulta_Curso_Asignado extends javax.swing.JFrame {
    
    private Estudiante cursosDesasignar = new Estudiante();
    private Estudiante estudianteSeleccionado = null;
    
    private void actualizarTabla(){
        DefaultTableModel data = new DefaultTableModel(new String[]{"ID", "Nombre", "Seccion", "Fecha inicio", "Fecha fin", "Hora inicio", "Hora fin", "Profesor", "Nota"}, estudianteSeleccionado.cursos.size());
        jTable1.setModel(data);

        int row = 0;

        for(int i = 0; i < estudianteSeleccionado.cursos.size(); i++){
            Curso c = estudianteSeleccionado.cursos.get(i);
            jTable1.setValueAt(c.id, row, 0);
            jTable1.setValueAt(c.nombre, row, 1);
            jTable1.setValueAt(c.seccion, row, 2);
            jTable1.setValueAt(c.fechaInicio, row, 3);
            jTable1.setValueAt(c.fechaFin, row, 4);
            jTable1.setValueAt(c.horaInicio, row, 5);
            jTable1.setValueAt(c.horaFin, row, 6);
            jTable1.setValueAt(c.profesor, row, 7);
            jTable1.setValueAt(estudianteSeleccionado.notaFinal.get(i), row, 8);
            row++;
        }
    }
    
    /**
     * Creates new form Panel_Consulta_Curso_Asignado
     */
    public Panel_Consulta_Curso_Asignado() {
        initComponents();
        Estudiante estudiante = new Estudiante();
        
        for (Estudiante e : ProyectoFinal.estudiantes){
            if (e.nombre.equals(ProyectoFinal.estudianteLogueado.nombre)){
                estudianteSeleccionado = e;
                break;
            }
        }
        
        if(estudianteSeleccionado != null){
            actualizarTabla();
        }
        
        
        
        //cursosDesasignar = estudiante.cursos.get(filaEscogida);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Desasignar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Consulta de cursos asignados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Desasignar.setText("Desasignar");
        Desasignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesasignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Desasignar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Desasignar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Panel_Estudiante panel_Estudiante = new Panel_Estudiante();
        panel_Estudiante.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DesasignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesasignarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            String idCurso = jTable1.getValueAt(filaSeleccionada, 0).toString();
            for (int i = 0; i < estudianteSeleccionado.cursos.size(); i++) {
                if (estudianteSeleccionado.cursos.get(i).id.equals(idCurso)) {
                    estudianteSeleccionado.cursos.remove(i);
                    ((DefaultTableModel) jTable1.getModel()).removeRow(filaSeleccionada);
                    JOptionPane.showMessageDialog(this, "Curso desasignado");
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "No se pudo encontrar el curso seleccionado en la lista de cursos del estudiante");
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna fila");
        }
    }//GEN-LAST:event_DesasignarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Desasignar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
